version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "jobRequest:8:1,qbes:64:1,qflow:64:1,jobOutput:64:1,jobStatusUpdate:64:1,dataSyncControl:1:1"
      KAFKA_NUM_NETWORK_THREADS: 64
      KAFKA_IO_THREADS: 64
      KAFKA_HEAP_OPTS: "-Xmx2g -Xms2g"
      KAFKA_MAX_REQUEST_SIZE: "10485760"
      KAFKA_MESSAGE_MAX_BYTES: "10485760"
  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-sync:/node-red-sync
    # entrypoint: >
    #   sh -c "
    #   npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict \
    #     @digitaloak/node-red-contrib-digitaloak-postgresql@~0.3.2 \
    #     node-red-contrib-custom-chatgpt@~1.2.11 \
    #     node-red-contrib-email@~0.2.1 \
    #     node-red-contrib-fs@~1.4.1 \
    #     node-red-contrib-kafka-client@~0.1.0 \
    #     node-red-contrib-kafka-manager@~0.5.1 \
    #     node-red-contrib-msg-speed@~2.1.0 \
    #     node-red-contrib-re-postgres@~0.3.4 \
    #     node-red-contrib-ui-etable@~4.6.3 \
    #     node-red-contrib-uibuilder@~6.0.0 \
    #     node-red-dashboard@~3.3.1 \
    #     node-red-node-email@~2.0.1 \
    #     node-red-node-ui-table@~0.4.3 \
    #     npm start -- --userDir /node-red-sync"
    # network_mode: host
    entrypoint: >
      sh -c "
      npm install --prefix /node-red-sync --unsafe-perm --no-update-notifier --no-fund --only=production
      && npm --no-update-notifier --no-fund start --cache /node-red-sync/.npm -- --userDir /node-red-sync"
    environment:
      - FLOWS=/node-red-sync/mc2.json
      - NODE_RED_USERNAME=admin
      - NODE_RED_PASSWORD=admin
      - TZ=UTC
    restart: always
    # command: npm start -- --userDir /data
networks:
  default:
volumes:
  node-red-sync:

#   npm install --prefix /node-red-sync --unsafe-perm --no-update-notifier --no-fund --only=production
# && npm --no-update-notifier --no-fund start --cache /node-red-sync/.npm -- --userDir /node-red-sync"